AllCops:
  RunRailsCops: true
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'bin/*'
    - 'Gemfile'
    - 'Guardfile'
    - 'Rakefile'
    - 'test/test_helper.rb'

Documentation:
  Enabled: false

StringLiterals:
  Enabled: false

LineLength:
  Max: 120

Style/MultilineOperationIndentation:
  Enabled: false

Metrics/MethodLength:
  CountComments: false  # count full line comments?
  Max: 12

Lint/AmbiguousRegexpLiteral:
  Enabled: false

Metrics/AbcSize:
  Enabled: false
